name: dhost
favicon: null
layout_spectrum: 0.9011238578241318
typography_spectrum: 0.3332675436977297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.043027886655181646
  lightness: 0.09737126366235316
  saturation: 0.18700387002900243
  rhythmicContrast: 0.013462799601256847
purpose: []
